project:
  type: website

website:
  title: "test-website"
  navbar:
    left:
      - href: index.qmd
      - href: posts/post1.qmd
      - href: posts/post2.qmd
      - href: posts/post3.qmd

format:
  html:
    theme: 
      - cosmo
      - styles.scss
